// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgXoKr_2YZ5pIQjV_JJQ8kIDCABA_OsAg',
    appId: '1:1013095085044:web:a1d277a199188d0de0ffa1',
    messagingSenderId: '1013095085044',
    projectId: 'zuri-app-ac760',
    authDomain: 'zuri-app-ac760.firebaseapp.com',
    storageBucket: 'zuri-app-ac760.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY1M2BvfL92Ar6LA8etf3fJZUBeAv5YLo',
    appId: '1:1013095085044:android:c2b583039e593f58e0ffa1',
    messagingSenderId: '1013095085044',
    projectId: 'zuri-app-ac760',
    storageBucket: 'zuri-app-ac760.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXwunt92CBGaVn2yb8LvqWFO8XJtj8mnU',
    appId: '1:1013095085044:ios:2b17dd55ebc8206fe0ffa1',
    messagingSenderId: '1013095085044',
    projectId: 'zuri-app-ac760',
    storageBucket: 'zuri-app-ac760.appspot.com',
    iosClientId: '1013095085044-qget7sc0saajcgl16o7tiu84t03m56m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.zuri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXwunt92CBGaVn2yb8LvqWFO8XJtj8mnU',
    appId: '1:1013095085044:ios:2b17dd55ebc8206fe0ffa1',
    messagingSenderId: '1013095085044',
    projectId: 'zuri-app-ac760',
    storageBucket: 'zuri-app-ac760.appspot.com',
    iosClientId: '1013095085044-qget7sc0saajcgl16o7tiu84t03m56m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.zuri',
  );
}
